### PR TITLE
Optimize filemeta for ListObjects operation.

### PR DESCRIPTION
**Pull request by iwanbk**
It optimizes by caching the resultof [Readdirnames](https://golang.org/pkg/os/#File.Readdirnames),
Which only contains the dir entries name.

The cache is considered invalid if current dir's ModTime is different/bigger than in the cache.

The cache is stored in LRU cache.

There are another improvements we could make.
- also cache whether the entry is directory or file.
- instead of using start index, the S3 paging  using object key as marker,
  we could also cache the position of object key that has been used as marker.

cc: @FastGeert @muhamadazmy

### CODE REVIEW

**Comment by FastGeert** [comment]
@iwanbk How much memory does the cache use when 1MIO files in 1 dir?

**Comment by iwanbk** [comment]
> @iwanbk How much memory does the cache use when 1MIO files in 1 dir?

depend on the length of the file, for the data itself is: length-of-filename MB.
So, if average length of the file is 15 chars, then the data needs 15MB of memory.
Of course there will be some overhead from the data structure, but i think we can ignore it.

> Can we specify how much memory the cache can use maximally?

AFAIK from the existing lru cache library, we can only limit the number of directories we want to cache.

**Comment by iwanbk** [comment]
Just thinking that we could store the list of files in a  file (maybe in tmpfs for faster access).
And adding some kind  indexing for faster access.

**Comment by FastGeert** [comment]
Well, ok, 15mb for 1mio files is ok, even with a bit of overhead.

I saw that here and there is still some commented code left behind. I don't like that. So please, clean these up, and merge ;-)

**Pull request merged**
